spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dio_projeto_board?useSSL=false&serverTimezone=UTC
    username: root
    password: jackson123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
